Feature/#987 buttons update
ratifire/devrate-web pull request #1024
Opened 2024-12-07 19:31 UTC by SamZakharov

2024-12-07 20:03 UTC, BhdnS commented on package.json
> +    "js-cookie": "^3.0.5",
Нужно удалить зависимость

2024-12-07 20:03 UTC, BhdnS commented on package.json
> +    "react-cookie": "^7.1.4",
Нужно удалить зависимость

2024-12-10 09:22 UTC, VladimirShaitan requested changes

2024-12-10 09:22 UTC, VladimirShaitan commented on src/components/FormsComponents/Buttons/ButtonDef/ButtonDef.jsx
> +  handlerClick: onClick,
`handlerClick ` треба прибрати звідси, таким чином щоб функція потрапляла в в `...props`

При виклику повинно виглядати `<ButtonDef onClick='func' />`

2024-12-12 21:25 UTC, SamZakharov commented on src/components/FormsComponents/Buttons/ButtonDef/ButtonDef.jsx
> +  handlerClick: onClick,
fixed

2024-12-13 09:32 UTC, VladimirShaitan approved these changes

2024-12-13 11:06 UTC, merged