add white theme to schedule step2
ratifire/devrate-web pull request #782
Opened 2024-10-12 06:45 UTC by vplabunets

2024-10-12 10:51 UTC, SamZakharov approved these changes

2024-10-12 13:23 UTC, VladimirShaitan requested changes

2024-10-12 13:23 UTC, VladimirShaitan commented on src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
>        toast.success('Event was deleted', {
Це треба винести в файл перекладів

2024-10-12 13:23 UTC, VladimirShaitan commented on src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
>        toast.success('Event was deleted', {
і пройдись по файлам, перевір щоб всі строки були в файлах перекладів

2024-10-12 13:23 UTC, VladimirShaitan commented on src/components/PageComponents/ScheduleComponents/Schedule.jsx
> +        setTimeout(waitForCalendarRef, 0);
Нащо тут затримка ?

2024-10-12 13:23 UTC, VladimirShaitan commented on src/components/PageComponents/ScheduleComponents/Schedule.jsx
> +        setTimeout(waitForCalendarRef, 0);
нащо і тут затримка ?)

2024-10-13 14:00 UTC, vplabunets commented on src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
>        toast.success('Event was deleted', {
В календарі немає більше слів без перекладу.

2024-10-13 21:00 UTC, SamZakharov approved these changes

2024-10-16 08:58 UTC, VladimirShaitan approved these changes

2024-10-16 09:34 UTC, merged