Add empty maket on notification #604
ratifire/devrate-web pull request #787
Opened 2024-10-13 01:50 UTC by VladyslavDykyi

2024-10-13 14:04 UTC, vplabunets approved these changes

2024-10-13 15:23 UTC, BhdnS approved these changes

2024-10-13 21:00 UTC, SamZakharov approved these changes

2024-10-14 10:31 UTC, VladimirShaitan requested changes

2024-10-14 10:31 UTC, VladimirShaitan commented on src/components/PageComponents/Notification/Notification.jsx
> +  const id = open ? 'simple-popover' : undefined;
Це що за перевірка така?
Хочаб null постав

2024-10-14 10:31 UTC, VladimirShaitan commented on src/components/PageComponents/Notification/NotificationItem/NotificationItem.jsx
> +        {iconMap[type || 'info']}
Тут треба десб визначити дефолтну іконку і не робити перевірку прямо в рендері.
Просто винеси в змінні назві дефолтної іконки і перевіряй це все перед return, таким чином презенатація буде відповідати тільки за презентацію і не буде включати в себе частини логіки

2024-10-14 10:31 UTC, VladimirShaitan commented on src/components/PageComponents/Notification/NotificationItem/NotificationItem.jsx
> +        { !read && <Chip label={t('notifications.newNotifications')} sx={styles.badge} onClick={markAsReadClickHandler} />}
якщо ще булеан то повинно назвитись змінна з префіксом **should** або **is** або **has**

2024-10-14 10:31 UTC, VladimirShaitan commented on src/redux/services/notificationsApiSlice.js
> +        const ws = new WebSocket(`${process.env.REACT_APP_WS_URL}/ws/notifications`);
ось цей шмат коду треба винести в якийсь конфігураційний файл 
Створи файл `socketsEndpoints.js` і винеси туди цей шлях `ws/notifications`
Так нехай там буде тільки 1 константа, якщо додадуться ще то будем туди їх зберігати

2024-10-14 10:31 UTC, VladimirShaitan commented on src/redux/services/notificationsApiSlice.js
> +          console.log('Error while fetching notification data.');
Не впевнений що тут треба лог, напевне при помилці фетчігу треба в компоненті де виводиться список нотифікацій вивести помилку по типу "Sorry something went wrong ..."

2024-10-14 10:31 UTC, VladimirShaitan commented on src/redux/store/store.js
> +//import logger from 'redux-logger';
Видалити

2024-10-16 19:35 UTC, VladimirShaitan requested changes

2024-10-16 19:35 UTC, VladimirShaitan commented on src/components/PageComponents/Notification/NotificationItem/NotificationItem.jsx
> +
```js
 const {role,scheduledDateTime} = JSON.parse(payload);
```

2024-10-16 19:35 UTC, VladimirShaitan commented on src/components/UI/TimeAgo/TimeAgo.jsx
> +    : t('notifications.lessThanHourAgo');
```js
const timeAgo = diffInHours >= 1 
    ? `${Math.floor(diffInHours)} ${t('notifications.hourAgo')}` 
    : t('notifications.lessThanHourAgo');
```

2024-10-16 19:35 UTC, VladimirShaitan commented on src/components/PageComponents/Notification/Notification.jsx
> +  const id = open ? 'simple-popover' : undefined;
```js
const id = open && 'simple-popover';
```

2024-10-16 19:35 UTC, VladimirShaitan commented on src/components/PageComponents/Notification/Notification.jsx
> +        {notifications?.length === 0 ?
Ось цей весь код jsx який лежить в цій модалці треба винести в окрему функцію на рівні цього компоненту

2024-10-16 19:35 UTC, VladimirShaitan commented on src/redux/services/notificationsApiSlice.js
> +          { updateCachedData,cacheDataLoaded,  cacheEntryRemoved },
```js
{ updateCachedData,cacheDataLoaded,  cacheEntryRemoved }
```

2024-10-16 19:35 UTC, VladimirShaitan commented on src/redux/services/notificationsApiSlice.js
> +          const listener = (event) => {
```js
const listener = ({data}) => {
```

2024-10-18 15:59 UTC, SamZakharov approved these changes

2024-10-18 23:42 UTC, BlackPuma9 approved these changes

2024-10-18 23:42 UTC, BlackPuma9 commented on src/components/PageComponents/Notification/NotificationItem/NotificationItem.jsx
> +  const currentUser = useSelector(selectCurrentUser);
its a minor thing, but just due to consistence of code
const { data: currentUser } = useSelector(selectCurrentUser);

2024-10-18 23:42 UTC, BlackPuma9 commented on src/components/PageComponents/Notification/NotificationItem/NotificationItem.jsx
> +NotificationItem.propTypes = {
would it be correct to write detailed props or better to keep it in general?
NotificationItem.propTypes = {
  data: PropTypes.shape({
    id: PropTypes.number.isRequired,
    read: PropTypes.bool.isRequired,
   ........
  }).isRequired,
};

2024-10-19 19:41 UTC, merged