Added some changes with a white theme in PersonalProfile.
ratifire/devrate-web pull request #793
Opened 2024-10-13 21:18 UTC by SamZakharov

I continue to implement the white theme

2024-10-13 21:26 UTC, VladyslavDykyi approved these changes

2024-10-14 10:21 UTC, VladimirShaitan requested changes

2024-10-14 10:21 UTC, VladimirShaitan commented on src/components/FormsComponents/Inputs/FormCheckbox/FormCheckbox.jsx
> +            styles.newsAgreementText}
Винести в змінну workExperience

2024-10-14 10:21 UTC, VladimirShaitan commented on src/components/PageComponents/ProfileComponents/PersonalProfile/RightSection/RightSection.jsx
> +            {/*</IconButtonDef>*/}
Думаю той закоментований код можна видалити

2024-10-14 13:52 UTC, SamZakharov commented on src/components/FormsComponents/Inputs/FormCheckbox/FormCheckbox.jsx
> +            styles.newsAgreementText}
Что ты имеешь ввиду?

2024-10-14 19:29 UTC, VladimirShaitan approved these changes

2024-10-14 19:30 UTC, merged