User names in calendar modal #808
ratifire/devrate-web pull request #821
Opened 2024-10-21 21:17 UTC by SamZakharov

2024-10-22 09:26 UTC, VladimirShaitan requested changes

2024-10-22 09:26 UTC, VladimirShaitan commented on src/pages/ShedulePage/SchedulePage.styles.js
>      // backgroundColor: theme.palette.mode==="dark" ? theme.palette.background.level2 :theme.palette.common.white,
Думаю це не треба

2024-10-22 09:26 UTC, VladimirShaitan commented on src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
>    console.log(event)
Видалити

2024-10-22 17:49 UTC, vplabunets approved these changes

2024-10-24 09:27 UTC, VladimirShaitan approved these changes

2024-10-27 19:07 UTC, merged