update registration form
ratifire/devrate-web pull request #828
Opened 2024-10-23 05:00 UTC by vplabunets

Corrected validation schema. Fix mistake in comparison of passwords. Added trim function.

2024-10-24 09:25 UTC, VladimirShaitan requested changes

2024-10-24 09:25 UTC, VladimirShaitan commented on src/utils/valadationSchemas/RegistrationSchema.js
> +            /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$&*?])[A-Za-z\d!@#$&*?]{8,}$/,
Ось цю регулярку винеси в окремий файл і перевикористай на песворд резет валідації

2024-10-24 09:25 UTC, VladimirShaitan commented on src/utils/valadationSchemas/ResetPasswordSchema.js
> +        /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$&*?])[A-Za-z\d!@#$&*?]{8,}$/,
Ось цю регулярку винеси в окремий файл і перевикористай на песворд резет валідації

2024-10-25 05:03 UTC, vplabunets commented on src/utils/valadationSchemas/ResetPasswordSchema.js
> +        /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$&*?])[A-Za-z\d!@#$&*?]{8,}$/,
Виправлено

2024-10-25 05:03 UTC, vplabunets commented on src/utils/valadationSchemas/RegistrationSchema.js
> +            /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$&*?])[A-Za-z\d!@#$&*?]{8,}$/,
Виправлено

2024-10-28 08:46 UTC, VladimirShaitan approved these changes

2024-10-28 17:41 UTC, merged