Feature/822
ratifire/devrate-web pull request #845
Opened 2024-10-25 21:29 UTC by SamZakharov

Finished work with modal for feedback.

2024-10-25 21:50 UTC, BhdnS commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +  const [error, setError] = useState(null);
Лучше один useState использовать. Там есть хук для этого, в utils -> hooks, для стейтов с несколькими полями. Ну или const [state, setState] = useState({ isLoading, isError });

2024-10-25 21:50 UTC, BhdnS commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +  const feedbackOptions = ['PROPOSITION', 'ISSUE', 'FEEDBACK'];
Константу лучше вынести за компонент, возможно в отдельный файл

2024-10-25 21:50 UTC, BhdnS commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +    formik.resetForm();
Состояние формы сбросится когда компонент размонтируется

2024-10-25 21:50 UTC, BhdnS commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +    },
InitialState лучше за пределы компонента вынести

2024-10-25 21:50 UTC, BhdnS commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +    validationSchema: FeedbackModal,
В проекте по другому называются схемы валидации: "FeedbackModalSchema"

2024-10-25 21:50 UTC, BhdnS commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +
Если error будет true, то как он отобразится? Лучше пусть только error отобразится в модальном окне, а не под титулкой и над формой

2024-10-25 21:50 UTC, BhdnS commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +      setError('Произошла ошибка при отправке. Попробуйте еще раз.');
Лучше сетить в ошибку из файла с переводами.

2024-10-25 21:50 UTC, BhdnS commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +      console.error('Ошибка отправки отзыва:', error);
Пользователь не будет смотреть ошибку в консоли

2024-10-25 21:50 UTC, BhdnS commented on src/components/PageComponents/Menu/Menu.jsx
> +          {/*</Link>*/}
Если кусок кода не нужен, то нужно удалить

2024-10-25 21:50 UTC, BhdnS commented on src/components/PageComponents/Menu/Menu.jsx
> +            label={t('Leave a Feedback')}
Этот перевод точно будет работать?

2024-10-25 21:50 UTC, BhdnS commented on src/utils/valadationSchemas/FeedbackModal.js
> +    .required('Введите сообщение'),
А зачем файл переводов, если здесь написал на одном языке?

2024-10-25 21:50 UTC, BhdnS commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +    setIsLoading(true);
isLoading можно взять из хука который возвращает RTK. Как-то так, например:
const [useHook, { isLoading, isError }] = useHookFromRTK;
Там ещё есть другие поля объекта.
Ещё у формика есть isSubmiting(Но это не точно)

2024-10-29 10:11 UTC, VladimirShaitan commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +      console.error('Submit Error:', error);
```js
 console.error('Submit Error:', error);
```
Я думаю тут треба рендирити снекбар на помилку замість консол ерор

2024-10-29 10:12 UTC, VladimirShaitan commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +      return () => clearTimeout(timeoutId);
Треба прибрати таймаут
```js 
  if (isSuccess) {
      setOpenSnackbarSuccess(true);
      const timeoutId = setTimeout(() => {
        handleClose();
      }, 2000);
      return () => clearTimeout(timeoutId);
```

2024-10-29 10:12 UTC, VladimirShaitan commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +          {/*{error?.data || 'An error occurred. Please try again.'}*/}
видали коментар

2024-10-29 10:13 UTC, VladimirShaitan commented on src/redux/services/api/apiSlice.js
> +          data: result.error.data || 'Too Many Requests. Please try again later.',
Тягнути з файлу перекладів

2024-10-29 10:13 UTC, VladimirShaitan commented on src/redux/services/api/apiSlice.js
> +        data: result.error.data || 'Request error',
Тягнути з файлу перекладів

2024-10-29 10:14 UTC, VladimirShaitan commented on src/utils/valadationSchemas/FeedbackProjectModalSchema.js
> +});
Тягнути з перекладів

```js
 select: Yup.string()
    .required('Выберите значение из списка'),
  feedbackText: Yup.string()
    .min(2, 'Минимум 2 символа')
    .max(300, 'Максимум 150 символов')
    .required('Введите сообщение'),
```

2024-10-29 10:15 UTC, VladimirShaitan commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +  const feedbackOptions = ['PROPOSITION', 'ISSUE', 'FEEDBACK'];
Винести в файл з константами

2024-10-29 10:15 UTC, VladimirShaitan commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +    formik.resetForm();
Компонент поки тримаємо відкритим тому стейт треба зкидувати вручну

2024-10-29 10:17 UTC, VladimirShaitan commented on src/utils/valadationSchemas/FeedbackModal.js
> +    .required('Введите сообщение'),
@BhdnS трохи легше )

2024-10-29 12:44 UTC, SamZakharov commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +  const feedbackOptions = ['PROPOSITION', 'ISSUE', 'FEEDBACK'];
я вынес в отдельный файл компонентно, если ошибка это  - перенесу в папку, где все константы лежат
![Screenshot_1](https://github.com/user-attachments/assets/31e3cdad-dc68-4eaa-9c44-dbaf1662a292)

2024-10-29 12:45 UTC, SamZakharov commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
> +    formik.resetForm();
скидываю значение таким образом
![image](https://github.com/user-attachments/assets/45026709-b2ca-4d81-938f-af2e5f4094ef)

2024-10-29 14:14 UTC, SamZakharov commented on src/redux/services/api/apiSlice.js
> +        data: result.error.data || 'Request error',
мне нужна помощь в решении этого момента

2024-10-29 18:41 UTC, VladimirShaitan requested changes
Додав світлу тему ?

2024-10-29 18:41 UTC, VladimirShaitan commented on src/components/PageComponents/Menu/Menu.jsx
> +            label={t('Leave a Feedback')}
```js
 label={t('Leave a Feedback')}
```

Це не буде працювати

2024-10-30 10:06 UTC, VladimirShaitan approved these changes

2024-10-30 10:18 UTC, merged