Edited menu
ratifire/devrate-web pull request #885
Opened 2024-11-01 16:44 UTC by SamZakharov

2024-11-04 13:12 UTC, VladimirShaitan requested changes
Треба поправити

2024-11-04 13:12 UTC, VladimirShaitan commented on src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
```js
setState({
  openSnackbarError: !!result.error,
  openSnackbarSuccess: !result.error,
});

```

2024-11-04 13:12 UTC, VladimirShaitan commented on src/components/PageComponents/Menu/Menu.jsx
>                  {...(link.name === 'profile.userMenu.logout' ? { onClick: logoutHandler } : {})}
```js
{...(link.name === 'profile.userMenu.logout' ? { onClick: logoutHandler } : {})}
Comment
```
цю умову краще винести з цендеру в тіло вфункції компоненту

2024-11-04 13:12 UTC, VladimirShaitan commented on src/components/PageComponents/Menu/Menu.jsx
> +  const order = (item) => item === 'profile.userMenu.logout' ? 'order: 2' : 'order: 0';
```js
const order = (item) => `order: ${item === 'profile.userMenu.logout' ? 2 : 0}`;

```

2024-11-05 15:04 UTC, VladyslavDykyi approved these changes

2024-11-05 17:29 UTC, VladimirShaitan approved these changes

2024-11-05 17:36 UTC, merged