refactor cancel event
ratifire/devrate-web pull request #895
Opened 2024-11-04 16:33 UTC by vplabunets

2024-11-04 20:06 UTC, VladimirShaitan approved these changes

2024-11-05 10:21 UTC, VladimirShaitan requested changes
Виправ будь ласка

2024-11-05 10:21 UTC, VladimirShaitan commented on src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
> +  console.log(event)
Видалити лог

2024-11-05 10:21 UTC, VladimirShaitan commented on src/components/PageComponents/ScheduleComponents/Schedule.jsx
>    // const fromTime = encodeURIComponent(`${specificDate.toFormat('yyyy-MM-dd')}T00:00:00+03:00`);
```js
  // const specificDate = DateTime.fromISO('2024-09-23T00:00:00+03:00');
  // const fromTime = encodeURIComponent(`${specificDate.toFormat('yyyy-MM-dd')}T00:00:00+03:00`);
  ```
  це нам потрібно ?
  Якщо ні то видали

2024-11-05 17:33 UTC, vplabunets commented on src/components/PageComponents/ScheduleComponents/Schedule.jsx
>    // const fromTime = encodeURIComponent(`${specificDate.toFormat('yyyy-MM-dd')}T00:00:00+03:00`);
Видалив

2024-11-05 17:33 UTC, vplabunets commented on src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
> +  console.log(event)
Видалив

2024-11-06 10:25 UTC, VladimirShaitan approved these changes

2024-11-06 13:09 UTC, merged